export type M6EvidenceLevel=
  |'VERIFIED'
  |'VERIFIED-STATIC-ORIGINAL'
  |'VERIFIED-HISTORICAL'
  |'RECOVERED_SECONDARY'
  |'INFERRED'
  |'SERVER-BOUNDARY'
  |'RECONSTRUCTION_POLICY'
  |'UNVERIFIED';

export const S28_RECONSTRUCTION_PROVENANCE='RECONSTRUCTION_POLICY' as const;
