import {test} from 'node:test';
import assert from 'node:assert/strict';
import {validateAnimation,frameIndex,advanceClock,safePath,validateCollision} from '../src/model.ts';
import {rawCell,findRoute,referenceCellToScreen,referenceScreenToCell,closestWalkable,directionFor} from '../src/coordinates.ts';
import {beginBattle,useAttack,updateBattle,initialState} from '../src/battle.ts';
import {validateSave} from '../src/save.ts';
const anim=()=>({action_slot:'00',frames_per_direction:2,raw_timing:5,directions:Array.from({length:8},(_,d)=>[d*2,d*2+1]),spr_frame_count:16,frame_bounds:Array.from({length:16},(_,index)=>({index,left:-12,top:-42,right:12,bottom:2}))});
const grid=()=>({width:3,height:3,grid_order:'first-major',grid:[1,0,0,1,1,0,0,1,1]});
test('active direction rows only and wrapping',()=>{const a=validateAnimation(anim());assert.equal(frameIndex(a,7,3),15);assert.equal(frameIndex(a,0,-1),1);});
test('rejects out-of-bounds frame',()=>{const a=anim();a.directions[3][1]=16;assert.throws(()=>validateAnimation(a));});
test('rejects stale slots accidentally appended',()=>{const a=anim();a.directions[0].push(999999);assert.throws(()=>validateAnimation(a));});
test('rejects empty action and non-finite timing',()=>{assert.throws(()=>validateAnimation({...anim(),frames_per_direction:0}));assert.throws(()=>validateAnimation({...anim(),raw_timing:NaN}));});
test('bounds stay signed, right and bottom exclusive',()=>{const a=validateAnimation(anim());assert.equal(a.frame_bounds[0].right-a.frame_bounds[0].left,24);const b=anim();b.frame_bounds[0].bottom=-42;assert.throws(()=>validateAnimation(b));});
test('clock deterministic across steps',()=>{let s={cursor:0,elapsed:0};for(let i=0;i<100;i++)s=advanceClock(s.cursor,s.elapsed,10,160,4);assert.deepEqual(s,advanceClock(0,0,1000,160,4));});
test('invalid duration fails closed',()=>assert.throws(()=>advanceClock(0,0,10,0,4)));
test('path traversal and remote assets blocked',()=>{for(const p of ['../x','/root','https://x','x/%2e%2e','x\\y','x//y'])assert.throws(()=>safePath(p));assert.equal(safePath('characters/B100/00/animation.json'),'characters/B100/00/animation.json');});
test('collision dimensions strict',()=>{validateCollision(grid());assert.throws(()=>validateCollision({...grid(),grid:[1]}));});
test('first-major collision indexing',()=>{assert.equal(rawCell(grid(),[1,0]),1);assert.equal(rawCell(grid(),[0,1]),0);assert.equal(rawCell(grid(),[-1,0]),null);});
test('reference coordinate functions are deliberately not treated as inverses',()=>{const xy=referenceCellToScreen([0,1]);assert.deepEqual(xy,[32,32]);assert.notDeepEqual(referenceScreenToCell(...xy),[0,1]);});
test('negative pixel conversion preserves floor semantics',()=>{assert.deepEqual(referenceScreenToCell(-1,-1),[-1,-1]);});
test('route stays on walkable nodes',()=>{const c=grid(),r=findRoute(c,[0,0],[2,2]);assert.ok(r);assert.deepEqual(r[0],[0,0]);assert.deepEqual(r.at(-1),[2,2]);assert.ok(r.every(n=>rawCell(c,n)===1));});
test('blocked and unreachable paths rejected',()=>{assert.equal(findRoute(grid(),[0,0],[0,1]),null);const c=grid();c.grid=[1,0,0,0,0,0,0,0,1];assert.equal(findRoute(c,[0,0],[2,2]),null);});
test('nearest walkable is deterministic',()=>assert.deepEqual(closestWalkable(grid(),[2,0]),[1,0]));
test('direction ordering is explicit provisional policy',()=>{assert.equal(directionFor(0,1),0);assert.equal(directionFor(1,0),2);assert.equal(directionFor(0,-1),4);assert.equal(directionFor(-1,0),6);});
test('attack rejected outside battle',()=>assert.equal(useAttack(initialState(),'x',0,0,null).ok,false));
test('damage and cooldown do not permit button-spam',()=>{const s=beginBattle(0,0);assert.ok(useAttack(s,'dummy-melee',0,0,null).ok);const hp=s.enemies[0].hp;assert.equal(useAttack(s,'dummy-melee',0,0,null).ok,false);assert.equal(s.enemies[0].hp,hp);});
test('mana failure is atomic',()=>{const s=beginBattle(0,0);s.mp=1;const before=JSON.stringify(s);assert.equal(useAttack(s,'dummy-melee',0,0,{skill_id:1101,name:'hit',mp_cost:25,explanation:'',magic_pattern_id:1}).ok,false);assert.equal(JSON.stringify(s),before);});
test('invalid action parameters are atomic',()=>{const s=beginBattle(0,0);const before=JSON.stringify(s);assert.equal(useAttack(s,'dummy-melee',0,0,null,Number.NaN).ok,false);assert.equal(JSON.stringify(s),before);assert.equal(useAttack(s,'dummy-melee',0,0,null,-1).ok,false);assert.equal(JSON.stringify(s),before);});
test('out-of-range attack cannot damage target',()=>{const s=beginBattle(0,0);assert.equal(useAttack(s,'dummy-ranged',0,0,null).ok,false);assert.equal(s.enemies[1].hp,90);});
test('each of the six skill branches can execute',()=>{for(const skill_id of [1101,1201,1301,19101,19201,19301]){const s=beginBattle(0,0);assert.ok(useAttack(s,'dummy-melee',0,0,{skill_id,name:'skill',mp_cost:20,explanation:'',magic_pattern_id:1}).ok);assert.equal(s.mp,80);}});
test('shield reduces one enemy interval deterministically',()=>{const s=beginBattle(0,0);assert.ok(useAttack(s,'dummy-melee',0,0,{skill_id:1301,name:'shield',mp_cost:20,explanation:'',magic_pattern_id:3}).ok);updateBattle(s,1600,0,0);assert.equal(s.hp,118);assert.ok(s.shield>0);});
test('blind reduces only the selected enemy damage',()=>{const s=beginBattle(0,0);assert.ok(useAttack(s,'dummy-melee',0,0,{skill_id:19101,name:'blind',mp_cost:20,explanation:'',magic_pattern_id:181}).ok);updateBattle(s,1600,0,0);assert.equal(s.hp,114.5);assert.ok(s.enemies[0].blind>0);});
test('mana buff returns mana on a later damaging attack',()=>{const s=beginBattle(0,0);assert.ok(useAttack(s,'dummy-melee',0,0,{skill_id:19301,name:'mana',mp_cost:20,explanation:'',magic_pattern_id:183}).ok);assert.equal(s.mp,80);updateBattle(s,700,0,0);assert.ok(useAttack(s,'dummy-melee',0,0,null).ok);assert.equal(s.mp,86);});
test('victory awarded once',()=>{const s=beginBattle(0,0);s.enemies[0].hp=1;s.enemies[1].hp=0;useAttack(s,'dummy-melee',0,0,null);assert.equal(s.phase,'won');assert.equal(s.reward,10);for(let i=0;i<20;i++)updateBattle(s,100,0,0);assert.equal(s.reward,10);assert.equal(useAttack(s,'dummy-melee',0,0,null).ok,false);});
test('poison, defeat and terminal state are bounded',()=>{const s=beginBattle(0,0);s.hp=1;for(let i=0;i<20;i++)updateBattle(s,100,0,0);assert.equal(s.phase,'lost');assert.ok(s.hp>=0);const before=JSON.stringify(s);assert.equal(useAttack(s,'dummy-melee',0,0,null).ok,false);assert.equal(JSON.stringify(s),before);});
const save=()=>({version:1,pack:'pack',character:'100',x:32,y:32,gold:0,savedAt:'2026-09-15T00:00:00Z'});
test('save round trip validates',()=>assert.equal(validateSave(JSON.parse(JSON.stringify(save())),'pack',['100'],100,100).x,32));
test('save rejects foreign pack, unknown version and NaN',()=>{for(const patch of [{pack:'other'},{version:2},{x:NaN},{gold:-1},{character:'199'},{savedAt:'bad'}])assert.throws(()=>validateSave({...save(),...patch},'pack',['100'],100,100));});
test('roundtrip holds on even-parity cell lattice',()=>{for(let x=0;x<47;x++)for(let y=0;y<47;y++)if((x+y)%2===0)assert.deepEqual(referenceScreenToCell(...referenceCellToScreen([x,y])),[x,y]);});
