import test from 'node:test';
import assert from 'node:assert/strict';
import {M7_MONSTER_ARCHETYPES,M7_MONSTER_ARCHETYPE_CATALOG,M7_MONSTER_BALANCE_POLICY,M7_MONSTER_DIFFICULTY_MATRIX,M7_MONSTER_LEVEL_BANDS,S33_TRAINING_MILESTONE_CANDIDATES,dynamicDifficultyHint,validateM7MonsterCatalog,type MonsterCombatTrait} from '../src/content/monsters/monster-archetype-catalog.ts';
import {S17_MONSTER_VISUAL_CATALOG} from '../src/content/monsters/monster-visual-catalog.ts';

test('S30 exposes 18 fixed-level monster archetypes across all seven M7 bands',()=>{validateM7MonsterCatalog();assert.equal(M7_MONSTER_ARCHETYPES.length,18);assert.deepEqual(M7_MONSTER_LEVEL_BANDS.map(row=>[row.band,row.minLevel,row.maxLevel]),[['T1',1,5],['T2',6,15],['T3',16,25],['T4',26,35],['T5',36,45],['T6',46,55],['T7',56,65]]);for(const band of M7_MONSTER_LEVEL_BANDS)assert.ok(M7_MONSTER_ARCHETYPE_CATALOG.forBand(band.band).length>0);for(const monster of M7_MONSTER_ARCHETYPES)assert.equal(monster.fixedLevel,true);});
test('required combat roles are distinct data traits rather than HP-only skins',()=>{const required:MonsterCombatTrait[]=['melee','high-attack-low-defense','high-defense-low-attack','fast','ranged','tank','dot','control','magic','healer','elite','boss'];for(const trait of required)assert.ok(M7_MONSTER_ARCHETYPE_CATALOG.withTrait(trait).length>0,trait);const fast=M7_MONSTER_ARCHETYPE_CATALOG.require('m7-blue-polearm-skirmisher-l5');const tank=M7_MONSTER_ARCHETYPE_CATALOG.require('m7-green-armored-bulwark-l36');const caster=M7_MONSTER_ARCHETYPE_CATALOG.require('m7-cyan-spectral-venom-caster-l42');assert.ok(fast.movementRange>tank.movementRange);assert.ok(tank.defense>fast.defense);assert.ok(caster.magicAttack>caster.attack);assert.ok(caster.abilities.some(row=>row.kind==='poison-dot'));});
test('healing monster is a direct Ash/healingBlocked acceptance target',()=>{const healer=M7_MONSTER_ARCHETYPE_CATALOG.require('m7-green-armored-renewer-l26');assert.ok(healer.traits.includes('healer'));assert.equal(healer.recoveryCapability?.kind,'self-heal');assert.equal(healer.recoveryCapability?.blockedByStatus,'healingBlocked');assert.equal(healer.recoveryCapability?.evidenceStatus,'RECONSTRUCTION_POLICY');assert.ok(healer.abilities.some(row=>row.kind==='self-heal'&&row.healHp===70));});
test('every visual binding resolves to manually reviewed fixed-client S17 resources',()=>{const families=new Set<string>();for(const monster of M7_MONSTER_ARCHETYPES){const visual=S17_MONSTER_VISUAL_CATALOG.require(monster.visualId);assert.equal(visual.sourceFamily,monster.visualFamily);assert.equal(monster.evidence.visualResource,'VERIFIED-STATIC-ORIGINAL');assert.equal(monster.evidence.visualBinding,'RECONSTRUCTION_POLICY');families.add(monster.visualFamily);}assert.deepEqual([...families].sort(),['B4524','B4525','B4526','B4544']);});
test('all offline monster numbers and abilities remain reconstruction policy',()=>{for(const monster of M7_MONSTER_ARCHETYPES){assert.equal(monster.evidenceStatus,'RECONSTRUCTION_POLICY');assert.equal(monster.evidence.combatNumbers,'RECONSTRUCTION_POLICY');assert.equal(monster.evidence.aiBehavior,'RECONSTRUCTION_POLICY');assert.equal(monster.evidence.abilities,'RECONSTRUCTION_POLICY');assert.equal(monster.evidence.retailEnemyStats,'SERVER-BOUNDARY');assert.equal(monster.evidence.retailEnemyAi,'SERVER-BOUNDARY');assert.equal(monster.evidence.fieldEncounterBinding,'SERVER-BOUNDARY');for(const ability of monster.abilities)assert.equal(ability.evidenceStatus,'RECONSTRUCTION_POLICY');}assert.equal(M7_MONSTER_BALANCE_POLICY.provenance,'RECONSTRUCTION_POLICY');assert.equal(M7_MONSTER_BALANCE_POLICY.playerLevelScaling,false);});
test('dynamic difficulty hint never scales or mutates enemy stats',()=>{const boss=M7_MONSTER_ARCHETYPE_CATALOG.require('m7-spectral-overseer-boss-l65');const before=JSON.stringify(boss);assert.equal(dynamicDifficultyHint(75,65),'Easy');assert.equal(dynamicDifficultyHint(65,65),'Normal');assert.equal(dynamicDifficultyHint(60,65),'Hard');assert.equal(dynamicDifficultyHint(50,65),'Very Hard');assert.equal(JSON.stringify(boss),before);assert.equal(boss.level,65);assert.equal(boss.maxHp,1580);});
test('difficulty matrix covers seven bands and all referenced monsters exist',()=>{assert.equal(M7_MONSTER_DIFFICULTY_MATRIX.length,7);for(const row of M7_MONSTER_DIFFICULTY_MATRIX){assert.ok(row.normalMonsterIds.length+row.hardMonsterIds.length+row.eliteBossMonsterIds.length>0);for(const id of [...row.normalMonsterIds,...row.hardMonsterIds,...row.eliteBossMonsterIds])M7_MONSTER_ARCHETYPE_CATALOG.require(id);}});
test('S33 handoff offers exactly the approved 15 recommended-level milestones',()=>{assert.deepEqual(S33_TRAINING_MILESTONE_CANDIDATES.map(row=>row.recommendedLevel),[2,5,6,10,15,16,25,26,35,36,45,46,55,56,65]);assert.equal(S33_TRAINING_MILESTONE_CANDIDATES.length,15);for(const row of S33_TRAINING_MILESTONE_CANDIDATES){assert.ok(row.candidateMonsterIds.length>0);row.candidateMonsterIds.forEach(id=>M7_MONSTER_ARCHETYPE_CATALOG.require(id));assert.equal(row.evidenceStatus,'RECONSTRUCTION_POLICY');}});
