import {expect,test} from '@playwright/test';
import {readFileSync} from 'node:fs';
import {renderGameShell} from '../src/ui/game-shell.ts';
import type {GameShellState} from '../src/ui/types.ts';
const css=readFileSync(new URL('../src/ui/game-shell.css',import.meta.url),'utf8');
const base:GameShellState={mode:'field',player:{name:'ViLeo',className:'剑士',portraitLabel:'剑',level:12,hp:112,hpMax:125,mp:64,mpMax:100,gold:1280},field:{mapId:1,mapName:'外城',questTitle:'训练委托',questDetail:'到训练场完成一次战斗，再回来复命。',interactionPrompt:'与训练官交谈'},menu:{open:false,canSave:true,canLoad:true,devEnabled:false},diagnostics:{open:false,mapSelector:'0001',rawTiming:'5 -> 200ms',actionSlot:'00',direction:'E / 6',bounds:'hidden',magicRes:'idle',provenance:'VERIFIED visual facts; reconstruction rules stay explicit.'},notice:'附近有可交互的 NPC'};
async function show(page:import('@playwright/test').Page,state:GameShellState){await page.setContent(`<!doctype html><html><head><meta charset="utf-8"><style>${css}</style></head><body style="margin:0">${renderGameShell(state)}</body></html>`);}
test('S8 field HUD visual harness',async({page})=>{await page.setViewportSize({width:1440,height:900});await show(page,base);await expect(page.locator('[data-ui="field-hud"]')).toBeVisible();await expect(page.locator('#developer-diagnostics')).toHaveCount(0);const widths=await page.evaluate(()=>({client:document.documentElement.clientWidth,scroll:document.documentElement.scrollWidth}));expect(widths.scroll).toBeLessThanOrEqual(widths.client);await page.screenshot({path:'test-results/s8-field-shell.png',fullPage:true});});
test('S8 battle HUD visual harness',async({page})=>{await page.setViewportSize({width:1440,height:900});await show(page,{...base,mode:'battle',notice:'目标已选择',battle:{phase:'active',readiness:16,readinessMax:20,ready:false,targetName:'训练守卫',targetHp:46,targetHpMax:80,statusText:'等待行动槽',canAttack:true,canRest:true,canReturn:false,skills:[{id:'slash',name:'重击',mpCost:8,hotkey:'1'},{id:'guard-break',name:'破甲',mpCost:12,hotkey:'2'}]}});await expect(page.locator('[data-ui="battle-hud"]')).toBeVisible();await expect(page.locator('[data-action="attack"]')).toBeDisabled();await page.screenshot({path:'test-results/s8-battle-shell.png',fullPage:true});});
test('S8 narrow layout avoids horizontal overflow and keeps diagnostics opt-in',async({page})=>{await page.setViewportSize({width:520,height:820});await show(page,{...base,menu:{...base.menu,devEnabled:true},diagnostics:{...base.diagnostics,open:false}});await expect(page.locator('[data-ui="field-hud"]')).toBeVisible();await expect(page.locator('#developer-diagnostics')).not.toHaveAttribute('open','');const widths=await page.evaluate(()=>({client:document.documentElement.clientWidth,scroll:document.documentElement.scrollWidth}));expect(widths.scroll).toBeLessThanOrEqual(widths.client);await page.screenshot({path:'test-results/s8-narrow-shell.png',fullPage:true});});
