export const PROVISIONAL = Object.freeze({
  evidence: 'UNVERIFIED' as const,
  frameDurationMs: 160,
  movementPixelsPerSecond: 96,
  attackDamage: 18,
  attackCooldownMs: 700,
  enemyDamage: 7,
  enemyIntervalMs: 1600,
  enemyHp: 90,
  meleeRadiusPx: 95,
  rangedRadiusPx: 300,
  effectDurationMs: 600,
  initialHp: 125,
  initialMp: 100,
  heavyDamage: 34,
  doubleDamage: 36,
  shieldDurationMs: 6000,
  manaBuffDurationMs: 6000,
  blindDurationMs: 5000,
  poisonDurationMs: 5000,
  poisonInitialDamage: 12,
  poisonDamagePerMs: 0.005,
  manaReturn: 6,
  damageReduction: 0.5,
  reward: 10,
  revision: 'training-policy-1',
});
export const ACTIONS: Record<string,string> = { '00':'待机', '01':'移动', '02':'攻击 / 施法', '03':'受击', '05':'特殊序列' };
export const DIRECTIONS = ['南','东南','东','东北','北','西北','西','西南'];
