export const PROVISIONAL = Object.freeze({
  evidence: 'UNVERIFIED' as const,
  frameDurationMs: 160,
  movementPixelsPerSecond: 96,
  attackDamage: 18,
  attackCooldownMs: 700,
  battleActionMax: 100,
  battleActionFillMs: 700,
  swordsmanMoveCells: 5,
  wizardMoveCells: 4,
  enemyDamage: 7,
  enemyIntervalMs: 1600,
  enemyHp: 90,
  meleeRadiusPx: 95,
  rangedRadiusPx: 300,
  effectDurationMs: 600,
  initialHp: 125,
  initialMp: 100,
  heavyDamage: 34,
  doubleDamage: 36,
  shieldDurationMs: 6000,
  manaBuffDurationMs: 6000,
  blindDurationMs: 5000,
  poisonDurationMs: 5000,
  poisonInitialDamage: 12,
  poisonDamagePerMs: 0.005,
  manaReturn: 6,
  damageReduction: 0.5,
  reward: 10,
  revision: 'battle-screen-policy-2',
});
export const ACTIONS: Record<string,string> = { '00':'待机', '01':'移动', '02':'攻击 / 施法', '03':'受击', '05':'特殊序列' };
// Real B100/B109 visual inspection: raw ANI rows run clockwise from south via west.
export const DIRECTIONS = ['南','西南','西','西北','北','东北','东','东南'];
